version: 1

url: https://forms.office.com/Pages/ResponsePage.aspx?id=XYP-cpVeEkWK4KezivJfyN7P4D2UeFpMrkrxKuoWldpUNDRBWDJEWEJIQ1JTS0RMSURYNElBQ1RIRyQlQCN0PWcu
answers:
  - generator: constant
    options:
      value: 'No'
